
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Arka G",
  "email": "arkap@gmail.com",
  "address": "345 Main Street",
  "dateOfBirth": "1980-06-24",
  "registeredDate": "2025-10-27"
}

###