
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Arka G 64 DB Block",
  "email": "bips@gmail.com",
  "address": "32 Park Street",
  "dateOfBirth": "1967-06-24",
  "registeredDate": "2024-10-27"
}

###