###Update existing patient details
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Bipasa G",
  "email": "adhig7@gmail.com",
  "address": "264 Main Street",
  "dateOfBirth": "1968-06-24"
}


###